### ISSUE TITLE
fix: gcc 9.2.0 error field_id missing on filter.c

### ISSUE THREAD

**Issue by ghost** [hhirsch/abook#2]
database.h line 64 remove the inline keyword from field_id(); otherwise cant compile on slackware64-current with gcc 9.2.0.

**Comment by hhirsch** [comment]
Thanks. Do you want to make a PR?

**Comment by ghost** [comment]
I think the project needs you in more matters, the autoconf need update. So many years I was lucky to use only make files; I have no experience to setup this.  I have no idea how I fix it, i tried autoreconf -i; aclocal-1.16; several other, I used even sed -i to fix some warnings...
Anyway, finally it worked and the I found the bug. I fix it, and everything working nicely.

**Comment by hhirsch** [comment]
Try current master and see if it is fixed.
